### ISSUE TITLE
Error instalando en MACOSX

### ISSUE THREAD

**Issue by Cu4rach4** [rocketbot-cl/rocketbot#1]
Buenas, hace un tiempo instale rocketbot studio sobre macosx mojave sin mayores inconvenientes, sin embargo al actualizar a Monterey no he logrado que funcione.

Error se genera al ejecutar el archivo "rocketbot":
`
-db=<su  DB> Selecciona una Base de datos / Select DataBase
-start=<su robot en DB> Ejecutar un script en Base de Datos / Run bot from DataBase
Loading:Endpoints
endpoints.a_debug.roc:endpoints.a_driverupdater.roc:endpoints.a_driverupdater.roc Error  EXCEPTION IN (rocketbot__, L_192 ""): No module named 'win32api'
EXCEPTION IN (rocketbot__, L_192 ""): No module named 'win32api'
endpoints.a_git.roc:endpoints.a_log_viewer.roc:endpoints.a_mods.roc:endpoints.a_treeview.roc:endpoints.a_varsbot.roc:endpoints.z_dev.roc:
ROCKETBOT Studio load in  http://localhost:5000?_=2022-04-29_18_18_03.522923`

Adicionalmente agrego para otros usuarios, que antes de la instalación se debe ejecutar el siguiente comando para que el sistema operativo no reclame por la procedencia de la aplicación:

`sudo spctl --master-disable`

**Comment by rocketbot-cl** [comment]
Hola @Cu4rach4 Es un error al cargar el addon para actualizar los drivers. No afecta el funcionamiento de Rocketbot. 
Al ser una beta, la recomendamos solo para usuarios windows por ahora. Si necesitas la versión estable, debes bajar desde la página https://rocketbot.com/rocketbot-studio-rpa/
